name: download-pages

# Controls when the workflow will run
on:
  schedule:
      # Run at the end of every day
      - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
      
      - name: Download pages
        run: python ./.github/workflows/download_pages.py --output-dir ./../pages/
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./../pages/
          git commit -m "Update pages" -a
        
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
